#!/bin/sh

### BEGIN INIT INFO
# Provides:          battery-monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Monitor laptop battery levels
# Description:       Send a global warning message and put the system to sleep
#                    when the battery is getting low.
### END INIT INFO

# Author: Jay R Bolton <jayrbolton@gmail.com>

NAME="battery-monitor"
DESC="Battery monitor"
PATH="/usr/sbin/$NAME"

# Include functions 
. /lib/lsb/init-functions

# Start daemon
start() {
  printf "Starting '$NAME'... "
  start-stop-daemon --start --background --make-pidfile --pidfile /var/run/$NAME.pid --exec "$PATH" || true
  printf "done\n"
}

# We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

# Stop the daemon
stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done 
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "done\n"
}

# Status of daemon
status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
